services:
  db:
    image: postgres:15
    container_name: restaurant_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./restaurant/Dockerfile
    container_name: restaurant_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./restaurant:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.docker

volumes:
  postgres_data:
