# Generated by Django 5.2.6 on 2025-09-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_time']},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('table', 'reservation_time'), name='unique_table_reservation'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
    ]
